// Show and hide activity spinner
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

// Update Button Padding Values
export const UPDATE_S_BTN_HORIZONTALPADDING = "UPDATE_S_BTN_HORIZONTALPADDING";
export const UPDATE_S_BTN_VERTICALPADDING = "UPDATE_S_BTN_VERTICALPADDING";
export const UPDATE_M_BTN_HORIZONTALPADDING = "UPDATE_M_BTN_HORIZONTALPADDING";
export const UPDATE_M_BTN_VERTICALPADDING = "UPDATE_M_BTN_VERTICALPADDING";
export const UPDATE_L_BTN_HORIZONTALPADDING = "UPDATE_L_BTN_HORIZONTALPADDING";
export const UPDATE_L_BTN_VERTICALPADDING = "UPDATE_L_BTN_VERTICALPADDING";

// Update Typography font sizes
export const UPDATE_DISPLAY_FONTSIZE = "UPDATE_DISPLAY_FONTSIZE";
export const UPDATE_H1_FONTSIZE = "UPDATE_H1_FONTSIZE";
export const UPDATE_H2_FONTSIZE = "UPDATE_H2_FONTSIZE";
export const UPDATE_H3_FONTSIZE = "UPDATE_H3_FONTSIZE";
export const UPDATE_H4_FONTSIZE = "UPDATE_H4_FONTSIZE";
export const UPDATE_H5_FONTSIZE = "UPDATE_H5_FONTSIZE";
export const UPDATE_H6_FONTSIZE = "UPDATE_H6_FONTSIZE";
export const UPDATE_SMALL_FONTSIZE = "UPDATE_SMALL_FONTSIZE";

// Update Table Header Color
export const UPDATE_TABLE_HEAD_COLOR = "UPDATE_TABLE_HEAD_COLOR";
export const UPDATE_TABLE_NARROW = "UPDATE_TABLE_NARROW";
export const UPDATE_TABLE_HOVERABLE = "UPDATE_TABLE_HOVERABLE";
export const UPDATE_TABLE_FULLWIDTH = "UPDATE_TABLE_FULLWIDTH";

// Update Theme Primary Color
export const UPDATE_THEME_PRIMARY_COLOR = "UPDATE_THEME_PRIMARY_COLOR";
