name: Publish

on:
  push:
    branches:
      - 2.0.0-dev

jobs:
  publish:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - name: Version Check
        uses: EndBug/version-check@v2.1.0
        id: check
      - run: npm publish --tag alpha.0 ./dist
        if: steps.check.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}