name: Publish

on:
  push:
    branches:
      - 2.0.0-dev

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish --tag alpha.0 ./dist 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}